version: "1.0"

services:
  postgres:
    container_name: np-postgresDb
    image: postgres:9.6
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
